# Generated by Django 4.2.4 on 2023-08-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'Skill', 'verbose_name_plural': 'Skill'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name': "Ko'nikmalar", 'verbose_name_plural': "Ko'nikmalar"},
        ),
    ]
