# Generated by Django 4.2.4 on 2023-08-19 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_messages_alter_skill_options_alter_skills_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='key',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
