# Generated by Django 4.2.4 on 2023-08-19 16:51

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/')),
                ('title', models.CharField(max_length=255)),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demo', models.URLField(default=True, null=True)),
                ('code', models.URLField(blank=True, null=True)),
                ('skills', models.ManyToManyField(blank=True, null=True, to='api.skill')),
            ],
        ),
    ]
