# Generated by Django 4.2.4 on 2023-08-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='demo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
