# Generated by Django 4.2.4 on 2023-08-19 17:15

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_projects_demo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='education/')),
                ('title', models.CharField(max_length=255)),
                ('desc', ckeditor_uploader.fields.RichTextUploadingField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='image',
            field=models.ImageField(default=1, upload_to='experience/'),
            preserve_default=False,
        ),
    ]
